import type { ScanReport, Finding, SecurityHeaderCheck, Technology } from "./types";

const findings: Finding[] = [
  {
    id: "f1",
    title: "Missing Content-Security-Policy Header",
    severity: "medium",
    category: "Security Headers",
    description: "The Content-Security-Policy header is not set, leaving the site vulnerable to cross-site scripting (XSS) and data injection attacks.",
    evidence: "Response headers do not include Content-Security-Policy",
    impact: "Attackers may inject malicious scripts that execute in users' browsers, potentially stealing session tokens or credentials.",
    recommendation: "Add a Content-Security-Policy header with a restrictive policy. Start with: Content-Security-Policy: default-src 'self'",
    reference: "https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP",
  },
  {
    id: "f2",
    title: "Strict-Transport-Security Max-Age Too Low",
    severity: "low",
    category: "Security Headers",
    description: "The HSTS max-age value is set to 300 seconds (5 minutes), which is significantly below the recommended minimum of 31536000 seconds (1 year).",
    evidence: "Strict-Transport-Security: max-age=300",
    impact: "Short HSTS duration reduces protection against SSL stripping attacks and may cause unnecessary redirects.",
    recommendation: "Set Strict-Transport-Security: max-age=31536000; includeSubDomains; preload",
  },
  {
    id: "f3",
    title: "X-Frame-Options Missing",
    severity: "medium",
    category: "Security Headers",
    description: "The X-Frame-Options header is not present. This may expose the site to clickjacking attacks.",
    evidence: "No X-Frame-Options header found in HTTP response",
    impact: "Attackers can embed this page in an invisible iframe on a malicious site to trick users into performing unintended actions.",
    recommendation: "Add X-Frame-Options: DENY or use Content-Security-Policy: frame-ancestors 'none'",
  },
  {
    id: "f4",
    title: "Referrer-Policy Not Set",
    severity: "low",
    category: "Security Headers",
    description: "No Referrer-Policy header is present. By default, browsers may send the full URL as a referrer, which could leak sensitive path information.",
    evidence: "No Referrer-Policy header in HTTP response",
    impact: "Internal URLs, session identifiers, or sensitive parameters may be leaked to third-party sites via the Referer header.",
    recommendation: "Add Referrer-Policy: strict-origin-when-cross-origin",
  },
  {
    id: "f5",
    title: "Server Version Disclosed",
    severity: "info",
    category: "Information Disclosure",
    description: "The server is disclosing its version in the Server response header.",
    evidence: "Server: Apache/2.4.51 (Unix)",
    impact: "Version disclosure assists attackers in identifying known vulnerabilities for the specific server version.",
    recommendation: "Configure your web server to suppress or genericize the Server header.",
  },
  {
    id: "f6",
    title: "robots.txt Exposes Internal Paths",
    severity: "info",
    category: "Reconnaissance",
    description: "The robots.txt file contains Disallow entries that reveal the existence of internal application paths.",
    evidence: "Disallow: /admin/, Disallow: /api/internal/, Disallow: /backup/",
    impact: "While robots.txt does not prevent access, it acts as a map for attackers to identify interesting endpoints.",
    recommendation: "Review robots.txt entries and consider whether path disclosure is acceptable. Use authentication to protect sensitive paths.",
  },
  {
    id: "f7",
    title: "Permissions-Policy Header Not Set",
    severity: "low",
    category: "Security Headers",
    description: "The Permissions-Policy header (formerly Feature-Policy) is not configured.",
    evidence: "No Permissions-Policy header found",
    impact: "Browser features such as camera, microphone, and geolocation may be accessible to embedded third-party content.",
    recommendation: "Add a Permissions-Policy header restricting features not needed by your application.",
  },
  {
    id: "f8",
    title: "Cross-Origin Resource Policy Not Set",
    severity: "info",
    category: "Security Headers",
    description: "The Cross-Origin-Resource-Policy header is absent.",
    evidence: "No CORP header in responses",
    impact: "Resources may be loaded cross-origin without restriction.",
    recommendation: "Consider adding Cross-Origin-Resource-Policy: same-origin where applicable.",
  },
  {
    id: "f9",
    title: "sitemap.xml Present",
    severity: "info",
    category: "Reconnaissance",
    description: "A sitemap.xml file is publicly accessible and enumerates site pages.",
    evidence: "HTTP 200 response at /sitemap.xml containing 47 URLs",
    impact: "Provides a complete site map to crawlers and potential attackers.",
    recommendation: "Informational only. Ensure sensitive endpoints are not listed.",
  },
];

const securityHeaders: SecurityHeaderCheck[] = [
  { name: "Strict-Transport-Security", present: true, value: "max-age=300", status: "warn", recommendation: "Increase max-age to at least 31536000" },
  { name: "Content-Security-Policy", present: false, status: "fail", recommendation: "Add a restrictive CSP policy" },
  { name: "X-Frame-Options", present: false, status: "fail", recommendation: "Add X-Frame-Options: DENY" },
  { name: "X-Content-Type-Options", present: true, value: "nosniff", status: "pass" },
  { name: "Referrer-Policy", present: false, status: "warn", recommendation: "Add Referrer-Policy: strict-origin-when-cross-origin" },
  { name: "Permissions-Policy", present: false, status: "warn", recommendation: "Configure Permissions-Policy for your use case" },
  { name: "Cross-Origin-Opener-Policy", present: false, status: "info" },
  { name: "Cross-Origin-Resource-Policy", present: false, status: "info" },
];

const technologies: Technology[] = [
  { name: "Nginx", category: "Web Server", version: "1.24.0", confidence: 95 },
  { name: "React", category: "JavaScript Framework", version: "18.x", confidence: 90 },
  { name: "Node.js", category: "Runtime", confidence: 75 },
  { name: "Cloudflare", category: "CDN / WAF", confidence: 88 },
  { name: "Google Analytics", category: "Analytics", confidence: 98 },
  { name: "Bootstrap", category: "CSS Framework", version: "5.x", confidence: 70 },
];

export const demoReport: ScanReport = {
  id: "demo-scan-001",
  target: "example.com",
  url: "https://example.com",
  scannedAt: "2026-08-26T14:32:00Z",
  profile: "standard",
  score: 8.7,
  grade: "A",
  status: "completed",
  findingCounts: { critical: 0, high: 0, medium: 2, low: 4, info: 7 },
  findings,
  securityHeaders,
  tls: {
    version: "TLS 1.3",
    cipher: "TLS_AES_256_GCM_SHA384",
    grade: "A",
    validUntil: "2027-03-15",
    issuer: "Let's Encrypt Authority X3",
    subjectAltNames: ["example.com", "www.example.com"],
  },
  dns: {
    a: ["93.184.216.34"],
    mx: ["mail.example.com"],
    ns: ["a.iana-servers.net", "b.iana-servers.net"],
    txt: ["v=spf1 -all"],
    hasDnssec: true,
    hasDmarc: false,
    hasSpf: true,
  },
  technologies,
  redirectChain: ["http://example.com", "https://example.com"],
  robotsTxt: true,
  sitemapXml: true,
  executiveSummary: "example.com demonstrates a strong overall security posture with no critical or high-severity findings. The TLS configuration is excellent with TLS 1.3 and a strong cipher. Primary areas for improvement include implementing a Content-Security-Policy header, strengthening the HSTS max-age value, and adding X-Frame-Options protection against clickjacking. Addressing the medium-severity findings would further improve the security score.",
  isDemoData: true,
};

export const mockScanHistory: ScanReport[] = [
  {
    ...demoReport,
    id: "scan-001",
    target: "example.com",
    url: "https://example.com",
    scannedAt: "2026-08-26T12:00:00Z",
    score: 8.9,
    grade: "A",
    isDemoData: true,
  },
  {
    ...demoReport,
    id: "scan-002",
    target: "client-site.com",
    url: "https://client-site.com",
    scannedAt: "2026-08-25T09:30:00Z",
    score: 7.1,
    grade: "B",
    findingCounts: { critical: 0, high: 1, medium: 3, low: 5, info: 4 },
    isDemoData: true,
  },
  {
    ...demoReport,
    id: "scan-003",
    target: "shop.example",
    url: "https://shop.example",
    scannedAt: "2026-08-24T16:15:00Z",
    score: 5.8,
    grade: "C",
    findingCounts: { critical: 0, high: 2, medium: 4, low: 6, info: 3 },
    isDemoData: true,
  },
  {
    ...demoReport,
    id: "scan-004",
    target: "api.startup.io",
    url: "https://api.startup.io",
    scannedAt: "2026-08-23T11:00:00Z",
    score: 9.2,
    grade: "A+",
    findingCounts: { critical: 0, high: 0, medium: 0, low: 2, info: 5 },
    isDemoData: true,
  },
];

export const scanProgressSteps = [
  "Target validation",
  "DNS reconnaissance",
  "TLS analysis",
  "Security headers",
  "Cookie inspection",
  "Redirect analysis",
  "robots.txt / sitemap",
  "Technology detection",
  "Report generation",
];
